pembelajaran_crud/Controllers/MakhlukHidupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using pembelajaran_crud.Data;
using pembelajaran_crud.Models;

namespace pembelajaran_crud.Controllers
{
    public class MakhlukHidupController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MakhlukHidupController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult LoadDataMakhluk()
        {
            try
            {
                var draw = Request.Form["draw"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();
                var length = Request.Form["length"].FirstOrDefault();
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
                var searchValue = Request.Form["search[value]"].FirstOrDefault();
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int recordsTotal = 0;

                MakhlukHidup makhluk = new MakhlukHidup(_context);
                var datamakhluk = makhluk.getDataMakhluk();


                if (!string.IsNullOrEmpty(searchValue))
                {
                    datamakhluk = datamakhluk.Where(m =>
                    m.nama_mk.ToLower().Contains(searchValue.ToLower()) ||
                    m.nama_asal.ToString().Contains(searchValue.ToLower())
                    );
                }
                recordsTotal = datamakhluk.Count();

                var data = datamakhluk.Skip(skip).Take(pageSize).ToList();

                var jsonData = new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data };
                return Ok(jsonData);
            }
            catch (Exception)
            {
                throw;
            }
        }

        public IActionResult PartialForm(string? action,string? id)
        {
            ViewBag.id = "";
            ViewBag.nama = "";
            ViewBag.tempatlahir = "";
            ViewBag.tanggal = "";
            ViewBag.jenis = "";
            ViewBag.asal = "";

            if (action == "edit")
            {
                var data = _context.makhluk_hidup.Where(x => x.mk_id.Equals(decimal.Parse(id)));
                foreach (var item in data)
                {
                    ViewBag.id = item.mk_id;
                    ViewBag.nama = item.nama_mk;
                    ViewBag.tempatlahir = item.tempat_lahir;
                    ViewBag.tanggal = item.tanggal_lahir.ToString("yyyy-MM-dd");
                    ViewBag.jenis = item.jenis_id;
                    ViewBag.asal = item.asal_id;
                }
            }
            return PartialView();
        }

        public IActionResult InsertUpdateData()
        {
            var id = Request.Form["id"];
            var action = "";
            var formdata = new MakhlukHidup.FormMakhluk();
            MakhlukHidup makhluk = new MakhlukHidup(_context);

            formdata.nama_mk = Request.Form["nama"];
            formdata.tempat_lahir = Request.Form["tempat"];
            formdata.tanggal_lahir = Request.Form["tanggal"];
            formdata.asal_id = Request.Form["asal"];
            formdata.jenis_id = Request.Form["jenis"];

            if (id != "")
            {
                action = "Diedit";
                formdata.mk_id = Request.Form["id"];
                makhluk.UpdateMakhluk(formdata);
            }
            else
            {
                action = "Ditambahkan";
                makhluk.InsertMakhluk(formdata);
            }
            return Ok("Data Berhasil "+ action);
        }

        public IActionResult DeleteData(string? id)
        {
            try
            {
                var _id = id;
                MakhlukHidup makhluk = new MakhlukHidup(_context);
                MakhlukHidup.FormMakhluk form = new MakhlukHidup.FormMakhluk();

                form.mk_id = _id;
                makhluk.DeleteMakhluk(form);

                return Ok("Data Berhasil Di Hapus!");
            }
            catch(DataException)
            {
                ModelState.AddModelError("", "Unable to Delete. Try again, and if the problem persists see your system administrator.");
                return Ok();
            }
        }

    }
}

pembelajaran_crud/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Belajar CRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/bootstrap-sweetalert/sweetalert.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/icofont/icofont.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/datatables/jquery.dataTables.min.js"></script>
    <script src="~/datatables/dataTables.bootstrap4.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/bootstrap-sweetalert/sweetalert.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Belajar CRUD</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MakhlukHidup" asp-action="Index">Daftar Makhluk</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - pembelajaran_crud - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @RenderSection("Scripts", required: false)

    <div class="modal show" id="modal-global" aria-modal="true">
        <div class="modal-dialog modal-xl">
            <div class="modal-content" id="contentmodal">
                <div class="modal-header">
                    <h4 class="modal-title">Modal Heading</h4>
                    <button type="button" class="close" data-dismiss="modal">×</button>
                </div>
                <!-- Modal body -->
                <div class="modal-body">

                </div>

            </div>
        </div>
    </div>
</body>
</html>